solving stack : Traceback (most recent call last):
  File "/home/mailman/py27/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/mailman/py27/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/home/mailman/hyperkitty/hyperkitty/views/accounts.py", line 101, in user_profile
    request.user.first_name, request.user.last_name)

  File "/home/mailman/mailman.client/src/mailmanclient/_client.py", line 634, in display_name
    self._info['display_name'] = value

TypeError: 'NoneType' object does not support item assignment